"use client";

import Link from "next/link";
import { useMemo, useRef, useState } from "react";
import { ArrowSquareOut, CheckCircle, EnvelopeSimple, Gear, ImageSquare, LockKey, MagnifyingGlass, Package, PaperPlaneTilt, SignOut, Storefront, Tag, Users, WarningCircle } from "@phosphor-icons/react";
import type { InquiryStatus, OperationsInquiries } from "@/lib/operations-inquiry-types";

type View = "all" | "open" | "replied" | "closed";
const labels: Record<View, string> = { all: "All inquiries", open: "Open", replied: "Replied", closed: "Closed" };

function dateTime(value: string) { return new Intl.DateTimeFormat("en-BS", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)); }
function relative(value: string) { const minutes = Math.max(1, Math.round((Date.now() - new Date(value).getTime()) / 60_000)); return minutes < 60 ? `${minutes}m ago` : minutes < 1440 ? `${Math.round(minutes / 60)}h ago` : dateTime(value); }
function statusLabel(status: InquiryStatus) { return status === "in_progress" ? "In progress" : status[0].toUpperCase() + status.slice(1); }

export function OperationsInquiriesConsole({ initialInquiries }: { initialInquiries: OperationsInquiries }) {
  const [data, setData] = useState(initialInquiries);
  const [view, setView] = useState<View>("open");
  const [query, setQuery] = useState("");
  const [selectedId, setSelectedId] = useState((initialInquiries.inquiries.find((item) => item.status === "new") || initialInquiries.inquiries[0])?.id || "");
  const [reply, setReply] = useState("");
  const [busy, setBusy] = useState(false);
  const replyIdRef = useRef<string | null>(null);
  const [notice, setNotice] = useState<{ tone: "success" | "error"; text: string } | null>(null);
  const selected = data.inquiries.find((item) => item.id === selectedId) || data.inquiries[0];
  const visible = useMemo(() => data.inquiries.filter((inquiry) => {
    const segment = view === "all" || (view === "open" ? inquiry.status === "new" || inquiry.status === "in_progress" : inquiry.status === view);
    const term = query.trim().toLowerCase();
    return segment && (!term || [inquiry.reference, inquiry.customerName, inquiry.customerEmail, inquiry.topic, inquiry.orderNumber || ""].join(" ").toLowerCase().includes(term));
  }), [data.inquiries, query, view]);

  async function refresh() { const response = await fetch("/api/operations/inquiries", { cache: "no-store" }); const body = await response.json() as OperationsInquiries & { error?: string }; if (!response.ok) throw new Error(body.error || "Client care could not be refreshed"); setData(body); }
  async function updateStatus(status: "new" | "in_progress" | "closed") { if (!selected) return; setBusy(true); setNotice(null); try { const response = await fetch("/api/operations/inquiries", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "status", inquiryId: selected.id, status }) }); const body = await response.json() as { error?: string }; if (!response.ok) throw new Error(body.error || "Inquiry could not be updated"); await refresh(); setNotice({ tone: "success", text: `${selected.reference} is ${statusLabel(status).toLowerCase()}.` }); } catch (caught) { setNotice({ tone: "error", text: caught instanceof Error ? caught.message : "Inquiry could not be updated" }); } finally { setBusy(false); } }
  async function sendReply() { if (!selected || reply.trim().length < 10) return; setBusy(true); setNotice(null); replyIdRef.current ||= crypto.randomUUID(); try { const response = await fetch("/api/operations/inquiries", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "reply", inquiryId: selected.id, message: reply.trim(), replyId: replyIdRef.current }) }); const body = await response.json() as { error?: string }; if (!response.ok) throw new Error(body.error || "Reply could not be sent"); setReply(""); replyIdRef.current = null; await refresh(); setNotice({ tone: "success", text: `Reply sent to ${selected.customerName}.` }); } catch (caught) { setNotice({ tone: "error", text: caught instanceof Error ? caught.message : "Reply could not be sent" }); } finally { setBusy(false); } }
  async function signOut() { await fetch("/api/operations/session", { method: "DELETE" }); window.location.assign("/operations/login"); }

  return <div className="operations-app operations-inquiries-app">
    <aside className="operations-sidebar"><div className="operations-wordmark">AURUM PRIVÉE</div><p className="operations-rail-label">Operations</p><nav aria-label="Operations navigation">
      <Link href="/operations"><Package size={21} weight="light" />Orders</Link><Link className="is-selected" href="/operations/inquiries"><EnvelopeSimple size={21} weight="light" />Client care</Link><Link href="/operations/catalog"><Tag size={21} weight="light" />Catalog</Link><Link href="/operations/images"><ImageSquare size={21} weight="light" />Product images</Link><Link href="/operations/customers"><Users size={21} weight="light" />Customers</Link><Link href="/operations/integrations"><Gear size={21} weight="light" />Integrations</Link>
    </nav><div className="operations-rail-utilities"><a href="/" target="_blank" rel="noreferrer"><ArrowSquareOut size={20} weight="light" />View storefront</a><button type="button" onClick={signOut}><SignOut size={20} weight="light" />Sign out</button></div></aside>
    <section className="operations-workspace"><header className="operations-topbar"><div><Storefront size={18} weight="light" /><span>Nassau store</span></div><div className="operations-sync"><EnvelopeSimple size={18} weight="light" />Client care</div></header><div className="operations-page-head operations-inquiries-page-head"><h1>Client care</h1><p>Read, reply to and resolve every fragrance and order inquiry.</p></div>{data.preview && <div className="operations-preview-banner"><WarningCircle size={17} weight="fill" />Local preview. Connect Supabase and Resend to send replies and work real inquiries.</div>}
      <div className="operations-frame operations-inquiries-frame"><section className="operations-queue operations-inquiries-queue"><div className="operations-summary operations-inquiries-summary"><button onClick={() => setView("all")}><span>Inquiries</span><strong>{data.totals.all}</strong></button><button onClick={() => setView("open")}><span>Open</span><strong>{data.totals.open}</strong></button><button onClick={() => setView("replied")}><span>Replied</span><strong>{data.totals.replied}</strong></button><button onClick={() => setView("closed")}><span>Closed</span><strong>{data.totals.closed}</strong></button></div><div className="operations-search-wrap"><MagnifyingGlass size={19} /><label className="sr-only" htmlFor="inquiry-search">Search inquiry or client</label><input id="inquiry-search" placeholder="Search inquiry or client" value={query} onChange={(event) => setQuery(event.target.value)} /></div><div className="operations-tabs" role="tablist">{(Object.keys(labels) as View[]).map((key) => <button key={key} role="tab" aria-selected={view === key} onClick={() => setView(key)}>{labels[key]}<span>{data.totals[key]}</span></button>)}</div>
        <div className="operations-inquiry-list">{visible.length ? visible.map((inquiry) => <button key={inquiry.id} className={selected?.id === inquiry.id ? "is-selected" : ""} onClick={() => { setSelectedId(inquiry.id); setReply(""); replyIdRef.current = null; setNotice(null); }}><span className={`operations-inquiry-dot is-${inquiry.status}`} /><span><strong>{inquiry.customerName}</strong><small>{inquiry.topic}{inquiry.orderNumber ? ` · ${inquiry.orderNumber}` : ""}</small><p>{inquiry.message}</p></span><span><i>{statusLabel(inquiry.status)}</i><small>{relative(inquiry.createdAt)}</small></span></button>) : <div className="operations-empty"><EnvelopeSimple size={30} weight="thin" /><h2>No inquiries here.</h2><p>Client notes matching this view will appear here.</p></div>}</div></section>
        <aside className="operations-inspector operations-inquiry-inspector">{selected && <><div className="operations-inquiry-title"><div><p className="utility-label">{selected.reference}</p><h2>{selected.topic}</h2><span className={`operations-status operations-status-${selected.status}`}>{statusLabel(selected.status)}</span></div></div><dl className="operations-inquiry-meta"><div><dt>Client</dt><dd>{selected.customerName}</dd></div><div><dt>Email</dt><dd>{selected.customerEmail}</dd></div>{selected.customerPhone && <div><dt>Phone</dt><dd>{selected.customerPhone}</dd></div>}<div><dt>Received</dt><dd>{dateTime(selected.createdAt)}</dd></div>{selected.orderNumber && <div><dt>Order</dt><dd><Link href={`/operations?order=${selected.orderNumber}`}>{selected.orderNumber}</Link></dd></div>}</dl><section className="operations-inquiry-message"><h3>Client’s note</h3><p>{selected.message}</p></section>{selected.replies.length > 0 && <section className="operations-inquiry-history"><h3>Replies</h3>{selected.replies.map((item) => <div key={item.id}><span>Sent {dateTime(item.sentAt)}</span><p>{item.message}</p></div>)}</section>}<section className="operations-reply-box"><label htmlFor="inquiry-reply">Reply to {selected.customerName}</label><textarea id="inquiry-reply" maxLength={4000} value={reply} onChange={(event) => setReply(event.target.value)} placeholder="Write a warm, useful reply…" /><div><small>{reply.length} / 4000</small><button className="operations-primary-button" disabled={busy || data.preview || reply.trim().length < 10} onClick={sendReply}><PaperPlaneTilt size={15} />{busy ? "Sending" : data.preview ? "Connect email" : "Send reply"}</button></div></section>{notice && <div className={`operations-notice is-${notice.tone}`} role="status">{notice.tone === "success" ? <CheckCircle size={18} weight="fill" /> : <WarningCircle size={18} weight="fill" />}{notice.text}</div>}<div className="operations-inquiry-actions"><button disabled={busy || data.preview} onClick={() => updateStatus(selected.status === "in_progress" ? "new" : "in_progress")}>{selected.status === "in_progress" ? "Move to new" : "Mark in progress"}</button><button disabled={busy || data.preview} onClick={() => updateStatus("closed")}>Close inquiry</button></div><p className="operations-customer-privacy"><LockKey size={14} />Only authorized Aurum Privée staff can read this conversation.</p></>}</aside></div>
    </section>
  </div>;
}
