import { Product } from "@/lib/types";

// Sample merchandise keeps the storefront fully explorable before Loyverse is connected.
// Replace this data through the protected Loyverse sync route before launch.
export const products: Product[] = [
  {
    id: "sample-iris-veil",
    slug: "iris-veil",
    brand: "Aurum Privée Edit",
    name: "Iris Veil",
    concentration: "Eau de parfum",
    size: "75 ml",
    price: 138,
    description: "A cool floral that opens softly, then settles into skin with fig, iris and clean woods.",
    family: "Floral",
    notes: { top: ["Bergamot", "Fig leaf"], heart: ["Iris", "Violet"], base: ["Cedar", "White musk"] },
    image: "/images/iris-veil.png",
    imageAlt: "Clear perfume bottle with fig and iris on a cool grey set",
    featured: true,
    newArrival: true,
    stock: 8,
  },
  {
    id: "sample-after-rain",
    slug: "after-rain",
    brand: "Aurum Privée Edit",
    name: "After Rain",
    concentration: "Eau de toilette",
    size: "100 ml",
    price: 116,
    description: "Green citrus, wet leaves and vetiver. Bright at first, mineral and close by evening.",
    family: "Fresh",
    notes: { top: ["Lime", "Petitgrain"], heart: ["Green tea", "Rain accord"], base: ["Vetiver", "Moss"] },
    image: "/images/hero-still-life.png",
    imageAlt: "Sculptural clear and violet fragrance bottles on smoked glass",
    featured: true,
    stock: 12,
  },
  {
    id: "sample-purple-hour",
    slug: "purple-hour",
    brand: "Maison Orphic",
    name: "Purple Hour",
    concentration: "Extrait de parfum",
    size: "50 ml",
    price: 184,
    description: "Black cherry and saffron against a deep sandalwood base, made for late dinners and slow arrivals.",
    family: "Amber",
    notes: { top: ["Black cherry", "Saffron"], heart: ["Rose", "Incense"], base: ["Sandalwood", "Amber"] },
    image: "/images/hero-still-life.png",
    imageAlt: "Deep plum perfume bottle on a smoked mirror plinth",
    featured: true,
    newArrival: true,
    stock: 4,
  },
  {
    id: "sample-skin-library",
    slug: "skin-library",
    brand: "Atelier June",
    name: "Skin Library",
    concentration: "Eau de parfum",
    size: "50 ml",
    price: 126,
    description: "A barely-there veil of ambrette, rice steam and pale woods that wears like warm skin.",
    family: "Woody",
    notes: { top: ["Ambrette", "Pear"], heart: ["Rice steam", "Orris"], base: ["Cashmere wood", "Musk"] },
    image: "/images/ritual.png",
    imageAlt: "Woman applying fragrance during a quiet morning ritual",
    stock: 6,
  },
  {
    id: "sample-salted-vanilla",
    slug: "salted-vanilla",
    brand: "Maison Orphic",
    name: "Salted Vanilla",
    concentration: "Eau de parfum",
    size: "75 ml",
    price: 144,
    description: "Vanilla bean cut with mineral salt and dry cedar. Comforting, polished and never overly sweet.",
    family: "Gourmand",
    notes: { top: ["Sea salt", "Pink pepper"], heart: ["Vanilla bean", "Heliotrope"], base: ["Cedar", "Tonka"] },
    image: "/images/iris-veil.png",
    imageAlt: "Minimal perfume bottle in directional studio light",
    stock: 9,
  },
  {
    id: "sample-night-bloom",
    slug: "night-bloom",
    brand: "Aurum Privée Edit",
    name: "Night Bloom",
    concentration: "Extrait de parfum",
    size: "50 ml",
    price: 172,
    description: "Tuberose after dark with plum skin and smoky patchouli. Lush, confident and beautifully persistent.",
    family: "Floral",
    notes: { top: ["Plum skin", "Mandarin"], heart: ["Tuberose", "Jasmine"], base: ["Patchouli", "Labdanum"] },
    image: "/images/ritual.png",
    imageAlt: "Woman in plum silk applying perfume by a window",
    stock: 3,
  },
];

export function getProductBySlug(slug: string) {
  return products.find((product) => product.slug === slug);
}

export function getProductsByIds(ids: string[]) {
  return products.filter((product) => ids.includes(product.id));
}
